spring.application.name=demo
server.port=${SERVER_PORT:8080}
spring.ai.ollama.chat.options.model=${OLLAMA_MODEL:gpt-oss:120b-cloud}
spring.ai.ollama.base-url=${OLLAMA_BASE_URL:http://host.docker.internal:11434}
